name: Chocolatey Package Deploy

on:
  push:
    branches:
      - master  # Adjust the branch name as needed

jobs:
  build-and-deploy:
    runs-on: windows-latest  # Chocolatey packaging typically runs on Windows

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Chocolatey
      run: |
        Set-ExecutionPolicy Bypass -Scope Process -Force; `
        iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))

    - name: Refresh environment variables
      run: RefreshEnv.cmd

    - name: Build Chocolatey package
      run: choco pack motion.nuspec

    - name: Push package to Chocolatey.org
      env:
        CHOCOLATEY_API_KEY: ${{ secrets.CHOCOLATEY_API_KEY }}
      run: choco push motion.nupkg --source=https://push.chocolatey.org/

